const flavorTexts = [
	"Also try Terraria!",
	"Now with more cloud!",
	"Powered by coffee!",
	"Made with love!",
	"99% bug free!",
	"Now in 3D!",
	"Awesome!",
	"Totally radical!",
	"Totally tubular!",
	"Kind of dragon free!",
	"More than 5000 sold!",
	"One of a kind!",
	"Heaps of hits on YouTube!",
	"Indev!",
	"Spiders everywhere!",
	"Check it out!",
	"Holy cow, man!",
	"It's a game!",
	"Made in Sweden!",
	"Uses LWJGL!",
	"Reticulating splines!",
	"Minecraft!",
	"Yaaay!",
	"Singleplayer!",
	"Pixels!",
	"Teetsuuuuoooo!",
	"Kaaneeeedaaaa!",
	"Now with extra hugs!",
	"Now Java 17!",
	"Very fun!",
	"You've got mail!",
	"100% pure!",
	"May contain traces of citrus!",
	"Who put TNT in my house?",
	"Open Source!",
	"Crunchy!",
	"Awesome community!",
	"Pancake powered!",
	"I need more context!",
	"Blame Mojang!",
	"You can't explain that!",
	"I bet Cylons wouldn't have this problem!",
	"From the streets of Soho!",
	"150% hyperbole!",
	"Does barrel rolls!",
	"Switches on and off!",
	"Technoblade never dies!",
	"Getting ready to show!",
	"Now with more exclamation marks!",
	"Woo, worldgen!",
	"Increasing FPS!",
	"Not on steam!",
	"12 herbs and spices!",
	"Not linear!",
	"Han shot first!",
	"Eple!",
	"Keyboards are overrated!",
	"Information wants to be free!",
	"Boots with the fur!",
	"Take her swimming on the first date!",
	"More digital!",
	"Follow the train, CJ!",
	"It's not a bug, it's a feature!",
	"Do the impossible, see the invisible!",
	"Never dig down!",
	"Take frequent breaks!",
	"Don't feed the creepers!",
	"Now with DLC!",
	"Seecret Friday update!",
	"Don't look directly at the bugs!",
	"Prepare to meet your spreadsheet!",
	"We fixed it!",
	"Respect the awesome!",
	"More than 16 million colors!",
	"What's up, gamers!",
	"Hot pizza delivered under 30 minutes or free!",
	"This message will never appear on the splash screen!",
	"No refunds!",
	"Voted most likely to succeed!",
	"Error 404: Joke not found!",
	"Warning: Contains code!",
	"Press any key to continue!",
	"Powered by Microsoft Azure!"
];
